Dataset Load

In [1]:
import pandas as pd

df = pd.read_csv("Books_Data_Clean.csv")

df.head()

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975.0,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,genre fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,genre fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015.0,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,genre fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008.0,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011.0,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,genre fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

Q1: Which genre appears most frequently in the dataset?

In [2]:
df["genre"].value_counts()

genre
genre fiction    822
nonfiction       171
fiction           62
children          15
Name: count, dtype: int64

Q2: Average (mean) Book_average_rating

In [3]:
df["Book_average_rating"].mean()

np.float64(4.007)

Q3: Publisher has highest TOTAL units sold?

In [23]:
publisher_units = df.groupby("Publisher")["units sold"].sum()
publisher_units.head()

Publisher
Amazon Digital Services,  Inc.        6074136
Hachette Book Group                    543821
HarperCollins Christian Publishing      41527
HarperCollins Publishers               563409
HarperCollins Publishing                44358
Name: units sold, dtype: int64

Q4: Missing values

In [ ]:
# df.isnull().sum()
# Book Name:
# Missing book names are replaced with "Unknown" because the book name is categorical/text data.
df["Book Name"] = df["Book Name"].fillna("Unknown")

# language_code:
# Missing language codes are replaced with "Unknown" because language code is categorical data.
df["language_code"] = df["language_code"].fillna("Unknown")

# Publishing Year:
# Missing publishing years are replaced with the median because it is numerical data
# and the median is less affected by extreme values.
df["Publishing Year"] = df["Publishing Year"].fillna(
    df["Publishing Year"].median()
)

df.head()

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975.0,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903,genre fiction,34160.0,20496.0,4.88,1,HarperCollins Publishers,7000
1,1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267,genre fiction,12437.5,7462.5,1.99,2,HarperCollins Publishers,6250
2,2,2015.0,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669,genre fiction,47795.0,28677.0,8.69,3,"Amazon Digital Services, Inc.",5500
3,3,2008.0,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898,fiction,41250.0,24750.0,7.50,3,Hachette Book Group,5500
4,4,2011.0,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283,genre fiction,37952.5,22771.5,7.99,4,Penguin Group (USA) LLC,4750

Q5: Sort dataset

In [27]:
# Sort the DataFrame by 'Publishing Year' from smallest to largest
df_sorted_by_year = df.sort_values(by='Publishing Year', ascending=True)
print("DataFrame sorted by 'Publishing Year' (smallest to largest):")
display(df_sorted_by_year.head(10))

DataFrame sorted by 'Publishing Year' (smallest to largest):

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
589,589,-560.0,Aesopica,"Aesop, Laura Harris, Laura Gibbs",eng,Excellent,4.05,88508,genre fiction,693.61,0.000,4.99,663,"Amazon Digital Services, Inc.",53784
990,990,-441.0,á¼ˆÎ½Ï„Î¹Î³ÏŒÎ½Î·,"Sophocles, J.E. Thomas",eng,Intermediate,3.60,67608,genre fiction,106.92,64.152,0.99,1167,"Amazon Digital Services, Inc.",108
293,293,-430.0,ÎŸá¼°Î´Î¯Ï€Î¿Ï…Ï‚ Î¤ÏÏÎ±Î½Î½Î¿Ï‚,"Sophocles, J.E. Thomas",eng,Intermediate,3.67,119496,genre fiction,2460.92,1476.552,7.99,315,Hachette Book Group,308
241,241,-380.0,Î Î¿Î»Î¹Ï„ÎµÎ¯Î±,"Plato, Desmond Lee",eng,Intermediate,3.90,110274,genre fiction,387.09,232.254,0.99,265,"Amazon Digital Services, Inc.",391
568,568,-300.0,é“å¾·ç¶“ [dÃ o dÃ© jÄ«ng],"Lao Tzu, Gia-Fu Feng, Jane English, Chungliang...",eng,Excellent,4.31,39863,genre fiction,665.55,399.330,4.59,632,Penguin Group (USA) LLC,3915
749,749,-17.0,Ã†neis,"Virgil, Robert Fitzgerald",eng,Intermediate,3.81,75051,genre fiction,114.84,0.000,0.99,863,"Amazon Digital Services, Inc.",31752
636,636,1308.0,La Divina Commedia,"Dante Alighieri, Allen Mandelbaum, Eugenio Mon...",eng,Excellent,4.06,74130,genre fiction,124.74,0.000,0.99,720,"Amazon Digital Services, Inc.",46008
446,446,1320.0,Inferno,"Dante Alighieri, Anthony M. Esolen",Unknown,Intermediate,3.99,87511,fiction,354.22,212.532,1.99,493,Hachette Book Group,4806
115,115,1390.0,Tales of Caunterbury,"Geoffrey Chaucer, Nevill Coghill",eng,Novice,3.48,148480,genre fiction,891.00,0.000,0.99,120,"Amazon Digital Services, Inc.",900
242,242,1593.0,The Taming of the Shrew,William Shakespeare,en-US,Intermediate,3.81,126318,nonfiction,2726.10,1635.660,6.99,266,Hachette Book Group,390